apache/eventmesh-site

.github/workflows/deploy.yml
docusaurus.config.js

The website will be built and published when contributors push or merge commits into the master branch.
Please create a new repository secret `DEPLOY_TOKEN` at [this page](https://github.com/apache/incubator-eventmesh-site/settings/secrets/actions). The value of the secret is the GitHub access token that can be generated at [this page](https://github.com/settings/tokens).
Demo: https://github.com/xiaoyang-sde/incubator-eventmesh-site/tree/asf-site

Setup GitHub Actions to build and deploy the website

---

blog/introducing-apache-eventmesh.md
docusaurus.config.js
package-lock.json
package.json

Setup Blog and post article 'Introducing Apache EventMesh'

---

docusaurus.config.js
src/pages/download.md

Setup Download page for download guides and links 

---

package-lock.json
package.json
src/pages/index.tsx
src/theme/Footer/index.tsx
src/theme/Footer/styles.module.css

Move Incubation Disclaimer to Footer

---

docusaurus.config.js
package-lock.json
package.json

Make the sidebar hideable for the docs page

Implement hideable sidebar

---

.gitignore
docusaurus.config.js
i18n/zh/code.json
i18n/zh/docusaurus-plugin-content-blog/options.json
i18n/zh/docusaurus-plugin-content-docs-community/current.json
i18n/zh/docusaurus-plugin-content-docs-events/current.json
i18n/zh/docusaurus-plugin-content-docs/current.json
i18n/zh/docusaurus-theme-classic/footer.json
i18n/zh/docusaurus-theme-classic/navbar.json
scripts/sync-docs.js

Sync the Chinese documents from apache/incubator-eventmesh

Sync the Chinese documents from apache/incubator-eventmesh

---

docusaurus.config.js

Update the link to the latest release note (v1.3.0)

Update the link to the latest release note (v1.3.0)

---

events/release-notes/v1.4.0.md

update 1.4.0 release notes

---

community/apache-release.md
docusaurus.config.js

1.update apache-release.md download link
2.update default page under events

Release update

---

src/pages/download.md

update 1.4.0 download links

---

blog/Meetup-content-review/Meetup-content-review.md
zh/blog/Meetup-content-review/Meetup-content-review .md

Meetup-content-review

---

team/01-member.md

Update team member

---

community/02-release.md

1. modify key server url and remove https://sks-keyservers.net(this url is gone)
2. change secretKeyRingFile path to absolute path
3. add signEnabled config field
4. add shasum cmd param(512)
5. add more description for release source file
6. change notice file description

change release file

---

docs/instruction/01-store-with-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/instruction/01-store-with-docker.md

- Translate the Chinese in the document
- update pull Rocketmq docker image

update Guidelines of eventmesh-store with Docker RocketMQ pull docker image

---

docs/design-document/01-workflow.md
i18n/zh/docusaurus-plugin-content-docs/current/design-document/01-workflow.md

- Fix AsyncAPI  official website is incorrect,

Fix AsyncAPI  official website is incorrect

---

docs/instruction/01-store-with-docker.md

Fix cd rocketmq dir incorrect

---

docs/sdk-java/01-intro.md
i18n/zh/docusaurus-plugin-content-docs/current/sdk-java/01-intro.md

Docusaurus provides the <Tabs> component 
Before:
Now:

polish sdk-java 01-intro.md document

---

i18n/zh/code.json
src/components/Hero.tsx

Translation Home Page.The rendering after translation is as follows

Translation Home Page

---

docs/introduction.md

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

Remove no longer avaiable LGTM badges

---

docs/instruction/01-store-with-docker.md
docs/instruction/01-store.md
i18n/zh/docusaurus-plugin-content-docs/current/instruction/01-store-with-docker.md
i18n/zh/docusaurus-plugin-content-docs/current/instruction/01-store.md

The previous modification was overwritten by the last merge. I will resubmit the pull request to optimize the way of obtaining the RocketMQ docker image.

polish pull rocketmq docker image

---

i18n/zh/docusaurus-plugin-content-docs/current/design-document/07-tracing.md

Translation Distributed Tracing doc (EN->CN)

Translation Distributed Tracing doc (EN->CN)

---

community/contribute/01-contribute.md

In the section of Documentation improvement a hyperlink was broken . improved that hyperlink.

[doc](01-contribute)fixed broken link.

---

docs/design-document/14-webhook.md

https://eventmesh.apache.org/docs/design-document/webhook

fix: markdown table for webhook

---

i18n/zh/docusaurus-plugin-content-pages/team.md
src/pages/team.md

[ISSUE #115]Add new Committer

---

docs/design-document/01-event-handling-and-integration/05-webhook.md
i18n/zh/docusaurus-plugin-content-docs/current/design-document/01-event-handling-and-integration/05-webhook.md

[ISSUE #138] Remind the difference between 10105 and 10106 ports

---

events/release-notes/v1.10.0.md

close #155 
- Add release notes

[ISSUE #155] Add release notes

---

events/release-notes/v1.0.0.md
events/release-notes/v1.1.0.md
events/release-notes/v1.1.1.md
events/release-notes/v1.10.0.md
events/release-notes/v1.2.0.md
events/release-notes/v1.3.0.md
events/release-notes/v1.4.0.md
events/release-notes/v1.5.0.md
events/release-notes/v1.6.0.md
events/release-notes/v1.7.0.md
events/release-notes/v1.8.0.md
events/release-notes/v1.9.0.md

close #160 
- Adjust the tab order in the sidebar of the release notes

[ISSUE #160]Adjust the tab order in the sidebar of the release notes

---

docs/instruction/06-operator.md
i18n/zh/docusaurus-plugin-content-docs/current/instruction/06-operator.md

deployment steps to improve eventmesh- operator documentation.

Deployment steps to improve eventmesh-operator documentation.

---

docs/design-document/03-connect/12-chatgpt-connector.md

Fixes #216
chatgpt connector doc

[ISSUE #216] Support chatGPT source connector

---

docs/design-document/03-connect/02-http-connector.md
docs/roadmap.md
i18n/zh/docusaurus-plugin-content-docs/current/design-document/03-connect/02-http-connector.md

[Doc] Add HTTP Sink Connector Document #220

[ISSUE #220] Add HTTP Sink Connector Document

---

.autocorrectignore
community/02-how-to-subscribe.md
community/04-release.md
community/05-how-to-vote-a-committer-pmc.md
docs/design-document/03-connect/02-http-connector.md
docs/design-document/03-connect/10-file-connector.md
docs/design-document/03-connect/11-kafka-connector.md

Fix used Chinese punctuation, spaces in the English contents.

---

src/theme/Footer/index.tsx

Fixes #229
*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*
Change the relative reference to the logo in src/theme/Footer/index.tsx: 81 to an absolute reference
- Does this pull request introduce a new feature? (yes / no)
- no

[ISSUE #229] Fix 404 issue due to setting log path to relative path

---

i18n/zh/docusaurus-plugin-content-pages/team.md
src/pages/team.md

Fixes #issue_id
*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*
*Describe the modifications you've done.*
- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

update team members
